# TODO - Docker compose 3 does not support service healthy yet: https://github.com/moby/moby/issues/30404
version: "2.1"
services:
  waveform-database:
    image: globaldevtools.bbva.com:5000/base/icuzr/docker-cassandra:feature-3.1.1
    volumes:
      - $PWD/database/waveform_clusters/migrations:/waveform_clusters/migrations
    healthcheck:
      test: cqlsh -e "DESCRIBE KEYSPACE waveform_clusters"
      interval: 4s
      timeout: 30s
      retries: 25
    environment:
      - CASSANDRA_KEYSPACES=waveform_clusters
      - CASSANDRA_HOSTS=waveform-database
################################################===CLUSTER===###########################################################
  cluster-service:
    image: globaldevtools.bbva.com:5000/base/icuzr/docker-alpine-waveform-runner
    working_dir: /go/src/github.com/flight
    volumes:
      - $PWD:/go/src/github.com/flight
    environment:
          - PORT=8080
          - CASSANDRA_HOSTS=waveform-database
          - CASSANDRA_KEYSPACE=waveform_clusters
    command: bash -c "./bin/clustersd"
    depends_on:
       waveform-database:
         condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://cluster-service:8080/v1/health"]
      interval: 4s
      timeout: 30s
      retries: 15
################################################===INTEGRATION TESTS===###########################################################
  integration-tests:
    image: globaldevtools.bbva.com:5000/base/icuzr/docker-debian-waveform-builder:feature-1.8.3
    working_dir: /go/src/github.com/flight
    environment:
      - CLUSTERSD_HOST=cluster-service
      - CLUSTERSD_PORT=8080
      - CLUSTERSD_VERSION=v1
      - CLUSTERSD_CASSANDRA_HOSTS=waveform-database
      - CLUSTERSD_CASSANDRA_KEYSPACE=waveform_clusters
    volumes:
      - $PWD:/go/src/github.com/flight
    depends_on:
      waveform-database:
         condition: service_healthy
    command: bash -c "./docker/scripts/runITest.sh"